# Generated by Django 5.0.4 on 2024-11-06 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OSConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operating_system', models.CharField(max_length=100)),
                ('config_type', models.CharField(max_length=100)),
                ('configuration_type', models.CharField(max_length=100)),
                ('packages', models.JSONField(default=list)),
                ('has_custom_wallpaper', models.BooleanField(default=False)),
                ('wallpaper', models.ImageField(blank=True, null=True, upload_to='wallpapers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
